baseurl = "https://arifsetwn.github.io/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Arif Setiawan"
title = "Arif Setiawan"
disqusshortname = "arifdewi"
googleAnalytics = "UA-45966046-1"
pluralizelisttitles = false


[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Life Start at ."
copyright = "Powered by Hugo"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "arifsetwn"
email = "arifsetwn@gmail.com"
#linkedin = "john-example-aa80ue8è"
twitter = "arip_se"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false
latestpostcount = 10