baseurl = "https://arifsetwn.github.io/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Arif Setiawan"
title = "Arif Setiawan"
disqusshortname = "arifdewi"
googleAnalytics = "UA-45966046-1"
pluralizelisttitles = false


[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Life Start at ."
copyright = "Powered by Hugo"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "arifsetwn"
email = "arifsetwn@gmail.com"
#linkedin = "john-example-aa80ue8è"
twitter = "arip_se"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false
latestpostcount = 10

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "box"

# Default JPEG quality setting. Default is 75.
quality = 75

# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
anchor = "smart"